# Generated by Django 3.1.2 on 2020-10-08 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='test', max_length=24)),
                ('last_name', models.CharField(default='test', max_length=24)),
                ('email', models.EmailField(default='test', max_length=32)),
                ('keeper', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=24)),
                ('species', models.CharField(default='test', max_length=72)),
                ('bio', models.CharField(default='test', max_length=180)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.user')),
            ],
        ),
    ]
