# Generated by Django 3.1.2 on 2020-10-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0003_auto_20201029_2328'),
        ('animals', '0002_donation_toy_wish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'Wishes'},
        ),
        migrations.AddField(
            model_name='user',
            name='zoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zoos.zoo'),
        ),
    ]
