# Generated by Django 3.1.2 on 2020-11-09 19:40

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20201029_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(animals.models.set_user_from_zoo), to='animals.user'),
        ),
    ]
