# Generated by Django 3.1.3 on 2020-11-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20201127_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='description',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='fund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
