# Generated by Django 3.1.2 on 2020-11-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0004_auto_20201109_1240'),
        ('animals', '0004_auto_20201109_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='zoo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='zoos.zoo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default='', max_length=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_first_name',
            field=models.CharField(default='', max_length=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_last_name',
            field=models.CharField(default='', max_length=72),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=72),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=24),
        ),
    ]
