# Generated by Django 3.1.3 on 2020-12-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20201129_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_last_name',
            new_name='last_name',
        ),
    ]
