# Generated by Django 3.1.2 on 2020-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('animals', '0005_auto_20201111_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
        migrations.AddField(
            model_name='toy',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
        migrations.AddField(
            model_name='wish',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
