# Generated by Django 3.1.2 on 2020-11-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20201115_1547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animals',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='donations',
        ),
        migrations.AlterModelTable(
            name='toy',
            table='toys',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='wish',
            table='wishes',
        ),
    ]
