# Generated by Django 3.1.3 on 2020-12-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20201210_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=72)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
    ]
