# Generated by Django 3.1.3 on 2020-12-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
    ]
