# Generated by Django 3.1.3 on 2020-12-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_remove_animal_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.species'),
        ),
    ]
