# Generated by Django 3.1.3 on 2021-01-04 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animal_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('website', models.CharField(max_length=72)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.CharField(help_text='Max 180 characters', max_length=180),
        ),
        migrations.AddField(
            model_name='toy',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.vendor'),
        ),
    ]
