# Generated by Django 3.1.3 on 2021-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20210103_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
