# Generated by Django 3.1.3 on 2021-01-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_toy_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='bio',
        ),
    ]
