# Generated by Django 3.1.3 on 2021-01-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_animal_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
