# Generated by Django 3.1.3 on 2021-01-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_auto_20210103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
