# Generated by Django 3.1.3 on 2021-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_auto_20210103_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='recent_img',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='sub_species',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
