# Generated by Django 3.1.3 on 2021-01-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_title'),
        ('animals', '0017_auto_20210105_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avatar_img', to='images.image'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.user'),
        ),
    ]
