# Generated by Django 3.1.3 on 2021-01-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_auto_20210106_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='species',
            field=models.ManyToManyField(to='animals.Species'),
        ),
    ]
