# Generated by Django 3.1.3 on 2021-01-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0021_auto_20210106_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_group',
            field=models.ManyToManyField(blank=True, to='animals.SpeciesGroup'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='suggested_species',
            field=models.ManyToManyField(blank=True, to='animals.SpeciesGroup'),
        ),
    ]
