# Generated by Django 3.1.3 on 2021-01-27 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0025_auto_20210106_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='brand',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 53, 55, 354154)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 53, 59, 699675)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.user'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 54, 6, 734585)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 54, 10, 908386)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 54, 21, 331830)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 54, 25, 378445)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 54, 31, 633152)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 54, 34, 428261)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 54, 38, 597570)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 54, 41, 533722)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 13, 54, 48, 124649)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 1, 27, 13, 54, 49, 784379)),
            preserve_default=False,
        ),
    ]
