# Generated by Django 3.1.3 on 2021-04-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0027_auto_20210307_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='url',
            field=models.URLField(max_length=1200, null=True),
        ),
    ]
