# Generated by Django 3.1.3 on 2021-04-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0028_auto_20210429_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='brand',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
