# Generated by Django 3.1.2 on 2021-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=72)),
                ('last_name', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=72)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'donations',
            },
        ),
    ]
