# Generated by Django 3.1.2 on 2021-07-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_auto_20210704_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='wish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.wish'),
        ),
    ]
