# Generated by Django 3.1.3 on 2020-12-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Untitled', max_length=90),
        ),
    ]
