# Generated by Django 3.1.2 on 2020-11-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20201111_2348'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
            options={
                'db_table': 'animal_images',
            },
        ),
        migrations.CreateModel(
            name='ToyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.toy')),
            ],
            options={
                'db_table': 'toy_images',
            },
        ),
        migrations.CreateModel(
            name='WishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.wish')),
            ],
            options={
                'db_table': 'wish_images',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
