# Generated by Django 3.1.3 on 2021-04-16 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
