# Generated by Django 3.1.2 on 2021-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Shipping address. Do not use main zoo address.', max_length=140),
        ),
    ]
