# Generated by Django 3.1.2 on 2020-10-30 05:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='accrs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AZA', 'Association of Zoos and Aquariums'), ('GFAS', 'Global Federation of Animal Sanctuaries'), ('EAZA', 'European Association of Zoos and Aquariums')], default=1, max_length=13),
            preserve_default=False,
        ),
    ]
