# Generated by Django 3.1.3 on 2021-01-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
