# Generated by Django 3.1.3 on 2021-01-04 03:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0002_zoo_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='accrs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AZA', 'Association of Zoos and Aquariums'), ('AAZK', 'American Association of Zookeepers'), ('GFAS', 'Global Federation of Animal Sanctuaries'), ('ZAA', 'Zoological Association of America')], max_length=17, null=True),
        ),
    ]
