# Generated by Django 3.1.2 on 2020-10-30 05:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0002_zoo_accrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='accrs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AZA', 'Association of Zoos and Aquariums'), ('GFAS', 'Global Federation of Animal Sanctuaries'), ('EAZA', 'European Association of Zoos and Aquariums')], max_length=13, null=True),
        ),
    ]
