# Generated by Django 3.1.3 on 2021-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0003_auto_20210103_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='street',
            field=models.CharField(help_text='Shipping address. Do not use main zoo address.', max_length=140, null=True),
        ),
    ]
