# Generated by Django 3.1.2 on 2020-11-13 06:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0004_auto_20201109_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='accrs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AZA', 'Association of Zoos and Aquariums'), ('AAZK', 'American Association of Zookeepers'), ('GFAS', 'Global Federation of Animal Sanctuaries'), ('EAZA', 'European Association of Zoos and Aquariums')], max_length=18, null=True),
        ),
    ]
