# Generated by Django 3.1.2 on 2020-11-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0005_auto_20201112_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='zip',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
