# Generated by Django 3.1.3 on 2021-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0005_auto_20210106_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='street',
            field=models.CharField(blank=True, help_text='Shipping address. Do not use main zoo address.', max_length=140, null=True),
        ),
    ]
