# Generated by Django 3.1.3 on 2021-03-08 04:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0006_auto_20210127_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
            preserve_default=False,
        ),
    ]
