# Generated by Django 3.1.2 on 2021-07-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_auto_20210704_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='New', max_length=72)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.wish')),
            ],
        ),
    ]
